import type { Metadata, Viewport } from "next";
import "./globals.css";
import { GridBackground } from "@/app/components/grid-background";

export const metadata: Metadata = {
  title: "Generic Roleplay Web",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#0a0a0b",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <GridBackground />
        <main className="relative z-10 flex flex-1 flex-col">{children}</main>
      </body>
    </html>
  );
}
